import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import logo from "@/public/logo.jpg"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex items-center justify-center">
          <div>
            <Image className="m-3" src={logo} alt="logo" width={100} height={100}/>
          </div>
          <div className="text-center w-full relative right-24">
            <h1 className="text-3xl font-semibold ">Recipe-Book</h1>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
